{{ if .Values.logsearchapi.enabled }}
{{ $logSearchValues := (. | mustDeepCopy) }}
{{ $_ := set $logSearchValues "common" (dict "nameSuffix" (include "logsearchapi.nameSuffix" .)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "logsearchapi.secretName" . }}
data:
  {{/*
  Those are passed to environment variables, which sets everything on startup
  There is no need to remember previously created secrets.
  */}}
  {{ $auditToken := randAlphaNum 32 }}
  auditToken: {{ $auditToken | b64enc }}
  queryToken: {{ randAlphaNum 32 | b64enc }}
  logQueryURL: {{ (printf "http://%v:8080" (include "common.names.fullname" $logSearchValues)) | b64enc }}
  webhookURL: {{ (printf "http://%v:8080/api/ingest?token=%v" (include "common.names.fullname" $logSearchValues) $auditToken) | b64enc }}
{{ end }}
