appVolumeMounts:
  export:
    emptyDir: true
    mountPath: /export
dnsConfig:
  options: []
emptyDirVolumes: true
environmentVariables: []
extraArgs: []
image:
  pullPolicy: IfNotPresent
  repository: minio/minio
  tag: RELEASE.2021-08-25T00-41-18Z
minioDomain: null
service:
  consolePort: 32325
  nodePort: 32324
updateStrategy: RollingUpdate
