# Default values for ix-chart.

image:
  repository: debian
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "testing"


# Update strategy
updateStrategy: "RollingUpdate"

# Container CMD / entrypoint
containerCommand: []
containerArgs: []
containerEnvironmentVariables: []

# Network related configuration
externalInterfaces: []

# Storage related configuration
hostPathVolumes: []
persistentVolumeClaims: []
