{{- if and (.Values.portForwardingList) (eq (include "hostNetworkingConfiguration" .) "false") }}
{{- $hostNet := .Values.hostNetwork }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ix-chart.fullname" . }}
  labels:
    {{- include "ix-chart.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    {{- range $index, $config := .Values.portForwardingList }}
      {{- if and (not $hostNet) (lt (int $config.nodePort) 9000) }}
        {{- fail (printf "Port (%s) is too low. Minimum allowed port is 9000." ($config.nodePort | toString)) }}
      {{- end }}
    - port: {{ $config.containerPort }}
      targetPort: {{ $config.containerPort }}
      protocol: {{ $config.protocol }}
      nodePort: {{ $config.nodePort }}
      name: ix-{{ $.Release.Name }}-{{ $config.nodePort }}-{{ $index }}
    {{- end }}
  selector:
    {{- include "ix-chart.selectorLabels" . | nindent 4 }}
{{- end }}
