{{ if .Values.logsearchapi.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "logsearchapi.secretName" . }}
data:
  {{/*
  Those are passed to environment variables, which sets everything on startup
  There is no need to remember previously created secrets.
  */}}
  {{ $auditToken := randAlphaNum 32 }}
  auditToken: {{ $auditToken | b64enc }}
  queryToken: {{ randAlphaNum 32 | b64enc }}
  webhookURL: {{ (printf "http://localhost:8080/api/ingest?token=%v" $auditToken) | b64enc }}
{{ end }}
