{{ if .Values.logsearchapi.enabled }}
{{ $values := (. | mustDeepCopy) }}
{{ $_ := set $values "common" (dict "nameSuffix" (include "logsearchapi.nameSuffix" .)) }}
{{ include "common.deployment.common_config" $values | nindent 0 }}
spec: {{ include "common.deployment.common_spec" $values | nindent 2 }}
  template: {{ include "common.deployment.pod.metadata" $values | nindent 4 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}-logsearchapi
        image: {{ include "logsearchapi.imageName" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env: {{ include "logsearchapi.envVariableConfiguration" $values | nindent 10 }}
        command: {{ include "logsearchapi.command" . }}
        ports:
        - name: logsearchapi
          containerPort: 8080
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /status
            port: 8080
          failureThreshold: 5
          periodSeconds: 15
          initialDelaySeconds: 15
        livenessProbe:
          httpGet:
            path: /status
            port: 8080
          failureThreshold: 5
          periodSeconds: 15
          initialDelaySeconds: 15
        startupProbe:
          httpGet:
            path: /status
            port: 8080
          failureThreshold: 5
          periodSeconds: 15
          initialDelaySeconds: 15
{{ end }}
