{{ if .Values.logsearchapi.enabled }}
{{ $dbPass := randAlphaNum 32 | b64enc }}
{{ $pgValues := (. | mustDeepCopy) }}
{{ $_ := set $pgValues "common" (dict "nameSuffix" (include "postgres.nameSuffix" .)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres.secretName" . }}
data:
  db_user: {{ include "postgres.dbUser" . }}
  db_name: {{ include "postgres.dbName" . }}
  {{ with (lookup "v1" "Secret" .Release.Namespace (include "postgres.secretName" .)) }}
  {{ $dbPass = (index .data "db_password") }}
  db_password: {{ $dbPass }}
  {{ else }}
  db_password: {{ $dbPass }}
  {{ end }}
  postgresURL: {{ printf "postgres://%v:%v@%v:5432/%v?sslmode=disable" (include "postgres.dbUser" .) ($dbPass | b64dec) (include "common.names.fullname" $pgValues) (include "postgres.dbName" .)  }}
{{ end }}
