## Set default image, imageTag, and imagePullPolicy. mode is used to indicate the
##
image:
  repository: ipfs/go-ipfs
  tag: v0.8.0-rc1
  pullPolicy: IfNotPresent

## Additional arguments to pass to ipfs binary
extraArgs: []

updateStrategy: RollingUpdate

service:
  nodePort: 9080

environment:
