apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ix-chart.fullname" . }}
  labels:
    {{- include "ix-chart.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "ix-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ix-chart.selectorLabels" . | nindent 8 }}
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
        {{- if .Values.externalInterfaces }}
        k8s.v1.cni.cncf.io/networks:
          {{- range $index, $iface := .Values.externalInterfaces }}
          - {{ include "externalInterfaceName" . }}-{{ $index }}
          {{- end }}
        {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.containerCommand }}
          command:
            {{- range .Values.containerCommand }}
            - {{ . | quote}}
            {{- end }}
          {{- end }}
          {{- if .Values.containerArgs }}
          args:
            {{- range .Values.containerArgs }}
            - {{ . | quote}}
            {{- end }}
          {{- end }}
          {{- if .Values.containerEnvironmentVariables }}
          env:
            {{- range .Values.containerEnvironmentVariables }}
            - name: {{ .name | quote }}
              value: {{ .value | quote }}
            {{- end }}
          {{- end }}
