apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ix-chart.fullname" . }}
  labels:
    {{- include "ix-chart.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "ix-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ix-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.container.command }}
          command:
            {{- range .Values.container.command }}
            - {{ . | quote}}
            {{- end }}
          {{- end }}
          {{- if .Values.container.args }}
          args:
            {{- range .Values.container.args }}
            - {{ . | quote}}
            {{- end }}
          {{- end }}
          {{- if .Values.container.environment_variables }}
          env:
            {{- range .Values.container.environment_variables }}
            - name: {{ .name | quote }}
              value: {{ .value | quote }}
            {{- end }}
          {{- end }}
