{{- range $index, $claim := .Values.persistentVolumeClaims }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ix-{{ $claim.name }}
spec:
  storageClassName: ix-storage-class-{{ $.Release.Name }}
  resources:
    requests:
      storage: {{ $claim.capacity }}
  accessModes:
    - ReadWriteMany
{{- end }}
