{{- $secretName := "db-details" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
data:
  db-user: {{ "postgres" | b64enc }}
  {{ with (lookup "v1" "Secret" .Release.Namespace $secretName) }}
  db-password: {{ index .data "db-password" }}
  {{ else }}
  db-password: {{ randAlphaNum 15 | b64enc }}
  {{ end }}
