appVolumeMounts:
  export:
    emptyDir: true
    mountPath: /export
postgresAppVolumeMounts:
  postgres-backup:
    emptyDir: true
    mountPath: /postgres_backups
  postgres-data:
    emptyDir: true
    mountPath: /var/lib/postgresql/data
postgresql:
  backupVolume:
    datasetName: ix-postgres_backups
    mountPath: /postgres_backups
  dataVolume:
    datasetName: ix-postgres_data
    mountPath: /var/lib/postgresql/data
ixChartContext: {}
distributedIps: []
distributedMode: false
dnsConfig:
  options: []
emptyDirVolumes: true
environmentVariables: []
extraAppVolumeMounts: []
extraArgs: []
image:
  pullPolicy: IfNotPresent
  repository: minio/minio
  tag: RELEASE.2022-11-10T18-20-21Z
logSearchImage:
  pullPolicy: IfNotPresent
  repository: minio/operator
  tag: v4.5.4
logsearchapi:
  enabled: true
  diskCapacityGB: 5
minioDomain: null
runAsGroup: 473
runAsUser: 473
service:
  consolePort: 32325
  nodePort: 32324
updateStrategy: RollingUpdate
