name: catalog_update

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest

    container:
      image: ixsystems/catalog_validation:latest

    steps:
      - uses: actions/checkout@v2
      - name: Update catalog details
        run: |
          /bin/bash -c "PWD=${pwd}; /usr/local/bin/catalog_update update --path $PWD"
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
            commit_message: Update catalog information
            file_pattern: 'catalog.json'
            commit_user_name: sonicaj
            commit_user_email: waqarsonic1@gmail.com
            commit_author: sonicaj <waqarsonic1@gmail.com>
